name: codestyle with PEP8 and tests

# on:
#   push:
#     branches:
#       - '**'
#   pull_request:
#     branches:
#       - develop
#       - master

# jobs:
#   codestyle:
#     name: Check codestyle PEP8
#     runs-on: ubuntu-latest
#     steps:
#     -
#       name: Check out the repo
#       uses: actions/checkout@v2
#     -
#       name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: 3.9
#     -
#       name: Install dependencies
#       run: |
#         python -m pip install --upgrade pip
#         pip install -r requirements/dev.txt
#     -
#       name: Lint with flake8
#       run: flake8 .
#     -
#       name: Codestyle by black
#       run: black --check .
#     -
#       name: Test with pytest
#       run: pytest
